Allow changing Traveler Boots speed using ThaumicBoots Keybinds.
GTNewHorizons/Electro-Magic-Tools pull request #75
Opened 2024-04-20 20:25 UTC by Drathonix

# Changes
EMT Traveler boots now implement IBoots (a new API feature I added in a PR on the ThaumicBoots repo)

EMT Traveler boots can now have their jump height and speeds changed.

2024-04-21 20:03 UTC, Drathonix commented
I've been having issues with maven local repos (literally no clue why I'm doing exactly what should be done) I've temporarily included the custom ThaumicBoots jar in the submission.

2024-04-21 20:04 UTC, Dream-Master commented
@Drathonix not forget to remove it after testing. i can do  pre tag on thaumic boots repo if you want?

2024-04-21 20:05 UTC, NotAPenguin0 requested changes

2024-04-21 20:05 UTC, NotAPenguin0 commented on lib/ThaumicBoots-1.2.1-master+4e33b9941e-dirty-dev.jar
Why is this file included?

2024-04-21 20:06 UTC, NotAPenguin0 commented on lib/ThaumicBoots-1.2.1-master+4e33b9941e-dirty-dev.jar
Didn't read above, sorry.

2024-04-21 20:09 UTC, Drathonix commented
@Dream-Master A pre tag would work.

2024-04-21 20:13 UTC, Alastors commented
"A new API feature" you just changed the name for no reason

2024-04-21 20:14 UTC, Alastors submitted a review, later dismissed
Mitch has already said no to Thaumic Boots being a hard dep

2024-04-21 21:01 UTC, Dream-Master commented
@Drathonix https://github.com/GTNewHorizons/ThaumicBoots/releases/tag/1.2.2-pre

2024-05-06 16:24 UTC, Alastors requested changes
Accept the PR to your branch and I'll approve and merge

2024-05-06 17:48 UTC, Alastors approved these changes

2024-05-06 17:48 UTC, merged